FROM python:3.10-slim

RUN mkdir -p /opt/project_data
COPY ./dagster_project/requirements.txt .
RUN pip install -r requirements.txt

# Add code location code
WORKDIR /opt/dagster/app
COPY ./dagster_project /opt/dagster/app
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

# Run dagster code server on port 4000
EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors to execute runs and steps
CMD ["dagster", "code-server", "start" , "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"
CMD ["dagster","api", "grpc",  "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]